- name: Deploy app to Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Apply deployment
      command: kubectl apply -f "{{ lookup('env','WORKSPACE') }}/k8s/deployment.yaml"

    - name: Apply service
      command: kubectl apply -f "{{ lookup('env','WORKSPACE') }}/k8s/service.yaml"
